### ISSUE TITLE
Problem with launching SpeechCommandRecognition.py

### ISSUE THREAD

**Issue by TeemCh** [matlab-deep-learning/coexecution_speech_command#1]
I've error message saying:

C:\python_path\lib\site-packages\numpy\__init__.py:148: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init

I've installed mkl package but it didn't help

I've also executed **pyenv('ExecutionMode','OutOfProcess')**  command so that there's no conflict with shared packages but no good. What's the matter?

*Update
I've reinstalled numpy and repeated steps above it helped but now I have another issue:

Error using [py.SpeechCommandRecognition.SpeechCommandRecognition/initializeAcc](matlab:matlab.internal.language.introspective.errorDocCallback('py.SpeechCommandRecognition.SpeechCommandRecognition/initializeAcc'))
Calling inputname from scripts is not supported

What's last line means? Do I need to update my Matlab? I'm running 2021b

**Comment by jibrahim80** [comment]
Sorry for not noticing this issue earlier. 

I tried the code from MATLAB R2021b, and it works, so there is no need to update your MATLAB.

Do you still see the issue?
